server:
  port: ${PRODUCTSERVICE_PORT:8081}

spring:
  application:
    name: productservice
  datasource:
    url: ${PRODUCTSERVICE_DB_URL:jdbc:postgresql://localhost:5432/products_db}
    username: ${PRODUCTSERVICE_DB_USER:postgres}
    password: ${PRODUCTSERVICE_DB_PASS:postgresql}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: ${PRODUCTSERVICE_SHOW_SQL:true}
    hibernate:
      ddl-auto: ${PRODUCTSERVICE_DDL_AUTO:create}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
    hostname: productservice