server:
  port: ${USERSERVICE_PORT:8083}

spring:
  application:
    name: userservice
  datasource:
    url: ${USERSERVICE_DB_URL:jdbc:postgresql://localhost:5432/users_db}
    username: ${USERSERVICE_DB_USER:postgres}
    password: ${USERSERVICE_DB_PASS:postgresql}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: ${USERSERVICE_SHOW_SQL:false}
    hibernate:
      ddl-auto: ${USERSERVICE_DDL_AUTO:create}

jwt:
  secret: ${JWT_SECRET:tienda-app-jwt-secret-key-change-this-in-production-please}
  expiration: ${JWT_EXPIRATION:86400000}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
    hostname: userservice
